using System.Text;
using ArchLinterNet.Core.Model;

namespace ArchLinterNet.Core.Contracts;

// Serialization and parsing for the reviewed public API snapshot file.
//
// The file is a generated artifact reviewed as a diff, so serialization is deliberately
// environment-free: no timestamps, no paths, no machine or user names, no tool version stamp.
// Capturing the same surface twice produces byte-identical output on any host, which is what makes
// "the snapshot changed" a reviewable signal rather than noise.
public static class PublicApiSnapshotFormat
{
    public const string FormatIdentifier = "arch-linter-net/public-api-snapshot";
    public const int CurrentVersion = 1;

    // Bounds exist so a corrupt or hostile file fails deterministically instead of being read into
    // memory unbounded. They are far above any realistic reviewed surface.
    public const int MaxEntries = 200_000;
    public const int MaxLineLength = 4_000;

    private const string FormatDirective = "@format";
    private const string VersionDirective = "@version";
    private const string ContractDirective = "@contract";
    private const string AssemblyDirective = "@assembly";

    private static readonly string[] _headerComment =
    {
        "# arch-linter-net public API snapshot — generated by 'arch-linter-net public-api capture'.",
        "# Review changes to this file like any other reviewed artifact; do not edit it by hand.",
    };

    public static string Serialize(PublicApiSnapshotDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        StringBuilder builder = new();
        foreach (string comment in _headerComment)
        {
            AppendLine(builder, comment);
        }

        AppendLine(builder, $"{FormatDirective} {FormatIdentifier}");
        AppendLine(builder, $"{VersionDirective} {document.Version}");
        AppendLine(builder, $"{ContractDirective} {document.ContractId}");

        IEnumerable<IGrouping<string, PublicApiSnapshotEntry>> byAssembly = document.Entries
            .GroupBy(entry => entry.AssemblyName, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal);

        foreach (IGrouping<string, PublicApiSnapshotEntry> group in byAssembly)
        {
            AppendLine(builder, $"{AssemblyDirective} {group.Key}");
            foreach (string signature in group
                         .Select(entry => entry.Signature)
                         .Distinct(StringComparer.Ordinal)
                         .OrderBy(signature => signature, StringComparer.Ordinal))
            {
                AppendLine(builder, signature);
            }
        }

        return builder.ToString();
    }

    public static PublicApiSnapshotDocument Parse(string content, string sourceDescription)
    {
        ArgumentNullException.ThrowIfNull(content);

        int? version = null;
        string? contractId = null;
        bool formatSeen = false;
        string? currentAssembly = null;
        List<PublicApiSnapshotEntry> entries = new();

        string[] lines = content.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            int lineNumber = i + 1;

            if (line.Length > MaxLineLength)
            {
                throw Invalid(sourceDescription, lineNumber,
                    $"line exceeds the maximum supported length of {MaxLineLength} characters.");
            }

            string trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed[0] == '#')
            {
                continue;
            }

            if (trimmed[0] == '@')
            {
                (version, contractId, currentAssembly, formatSeen) =
                    ApplyDirective(trimmed, sourceDescription, lineNumber, version, contractId, currentAssembly, formatSeen);
                continue;
            }

            if (currentAssembly == null)
            {
                throw Invalid(sourceDescription, lineNumber,
                    $"signature entry appears before any '{AssemblyDirective}' directive.");
            }

            if (entries.Count == MaxEntries)
            {
                throw Invalid(sourceDescription, lineNumber,
                    $"snapshot exceeds the maximum supported entry count of {MaxEntries}.");
            }

            entries.Add(new PublicApiSnapshotEntry(currentAssembly, trimmed));
        }

        if (!formatSeen)
        {
            throw Invalid(sourceDescription, line: null,
                $"missing '{FormatDirective} {FormatIdentifier}' directive.");
        }

        if (version == null)
        {
            throw Invalid(sourceDescription, line: null, $"missing '{VersionDirective}' directive.");
        }

        return new PublicApiSnapshotDocument(version.Value, contractId ?? string.Empty, entries);
    }

    private static (int? Version, string? ContractId, string? CurrentAssembly, bool FormatSeen) ApplyDirective(
        string trimmed,
        string sourceDescription,
        int lineNumber,
        int? version,
        string? contractId,
        string? currentAssembly,
        bool formatSeen)
    {
        (string name, string value) = SplitDirective(trimmed);

        switch (name)
        {
            case FormatDirective:
                if (!string.Equals(value, FormatIdentifier, StringComparison.Ordinal))
                {
                    throw Invalid(sourceDescription, lineNumber,
                        $"unsupported format '{value}'; expected '{FormatIdentifier}'.");
                }

                return (version, contractId, currentAssembly, true);

            case VersionDirective:
                if (!int.TryParse(value, out int parsedVersion) || parsedVersion != CurrentVersion)
                {
                    throw Invalid(sourceDescription, lineNumber,
                        $"unsupported snapshot version '{value}'; this build supports version {CurrentVersion}.");
                }

                return (parsedVersion, contractId, currentAssembly, formatSeen);

            case ContractDirective:
                return (version, value, currentAssembly, formatSeen);

            case AssemblyDirective:
                if (value.Length == 0)
                {
                    throw Invalid(sourceDescription, lineNumber, $"'{AssemblyDirective}' directive has no assembly name.");
                }

                return (version, contractId, value, formatSeen);

            default:
                throw Invalid(sourceDescription, lineNumber,
                    $"unknown directive '{name}'. Supported directives are " +
                    $"'{FormatDirective}', '{VersionDirective}', '{ContractDirective}', and '{AssemblyDirective}'.");
        }
    }

    private static (string Name, string Value) SplitDirective(string trimmed)
    {
        int separator = trimmed.IndexOf(' ', StringComparison.Ordinal);
        return separator < 0
            ? (trimmed, string.Empty)
            : (trimmed[..separator], trimmed[(separator + 1)..].Trim());
    }

    private static InvalidOperationException Invalid(string sourceDescription, int? line, string detail)
    {
        string location = line == null ? sourceDescription : $"{sourceDescription}:{line}";
        return new InvalidOperationException($"Invalid public API snapshot '{location}': {detail}");
    }

    // Always LF, never Environment.NewLine: the same surface must serialize byte-identically on
    // Windows and Unix, otherwise every cross-platform capture would show the whole file as changed.
    private static void AppendLine(StringBuilder builder, string value)
    {
        builder.Append(value).Append('\n');
    }
}
