<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\ArchLinterNet.Annotations\contentFiles\cs\any\**\*.cs" Link="Annotations\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
