coverage:
  precision: 2
  round: down
  range: "70..100"

comment:
  layout: "reach, diff, flags, tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  deletions_only: false

patch:
  default:
    target: 75
    threshold: 10%
    branches: null
    if_ci_failed: success
    if_not_found: success
    if_empty: success

  cli:
    paths:
      - src/ArchLinterNet.Cli/
    target: 60
    threshold: 20%
    if_ci_failed: success
    if_not_found: success
    if_empty: success

ignore:
  - "**/*.Tests/**"
  - "**/obj/**"
  - "**/bin/**"

flags:
  unittests:
    paths:
      - tests/
    carryforward: true
