namespace ArchLinterNet.Cli.Commands.Badge.Application.Setup;

internal sealed record BadgeSetupCommandOptions(
    string? InputPath,
    string? OutputDirectory,
    string? Repository,
    string? Visibility,
    string? Mode,
    string? DisclosureProfile,
    string? Account,
    string? Alias,
    string? Endpoint,
    string? ProviderPlan,
    int? CadenceMinutes,
    int? MaxLeaseMinutes,
    bool RenewalEnabled,
    bool DryRun,
    bool PublicDiagnostics,
    string Format,
    bool ShowHelp,
    long? RepositoryId = null,
    long? RepositoryOwnerId = null,
    string? BaseRef = null,
    string? PolicyPath = null,
    string? SolutionPath = null,
    string? CapabilityEvidencePath = null,
    string? ObservationPath = null,
    bool ApproveDisclosure = false,
    string? ProducerWorkflowPath = null,
    string? ProducerJobName = null,
    string? CheckName = null,
    string? CheckApp = null,
    string? ArtifactName = null,
    string? EvidenceArtifactName = null,
    string? Audience = null);
